message = 'welcome to python'
msg = message.capitalize()
print(msg)
msg = message.title()
print(msg)
msg = message.lower()
print(msg)
msg = message.upper()
print(msg)
msg = message.swapcase()
print(msg)
msg = message.count('o')
print(msg)
msg = message.find('python')
print(msg)
msg = message.index('python')
print(msg)
# msg = message.index('bob')
# print(msg)
# msg = message.find('bob')
# print(msg)
msg = message.isalnum()
print(msg)
msg = message.isdigit()
print(msg)
msg = message.islower()
print(msg)
msg = message.isupper()
print(msg)
# msg = message.split('')
# print(msg)
msg = message.split(' ')
print(msg)
