message = 'welcome to python'
msg = message.capitalize()
print(msg)
msg = message.title()
print(msg)
msg = message.lower()
print(msg)
msg = message.upper()
print(msg)
msg = message.swapcase()
print(msg)
msg = message.count('o')
print(msg)
msg = message.find('python')
print(msg)
msg = message.isnumeric()
print(msg)
msg = message.rfind('on')
print(msg)
msg = message.strip('python')
print(msg)
msg = message.index('python')
print(msg)
# msg = message.index('bob')
# print(msg)
# msg = message.find('bob')
# print(msg)
msg = message.isalnum()
print(msg)
msg = message.isdigit()
print(msg)
msg = message.islower()
print(msg)
msg = message.isupper()
print(msg)
msg = message.startswith('hello')
print(msg)
msg = message.endswith('study')
print(msg)

# msg = message.split('')
# print(msg)
msg = message.split(' ')
print(msg)
msg = message.split('o')
print(msg)
msg = message.join('**')
print(msg)
for_join = '**'
msg = message.join(for_join)
print(msg)
msg = for_join.join(message)
print(msg)
msg = message.center(50, '<')
print(msg)